### PR TITLE
Fix getWith should always return array.

### LINKED ISSUE #7: Setting $with as string with ModelTrait
The readme states, that the ModelTrait can be used as follows:

    protected $with = 'groups';
    // or
    protected $with = ['groups', 'permissions'];

When using the first option and using a string for a single relation, `ModelTrait->getWith` throws an error because it is supposed to return an array:

https://github.com/tattersoftware/codeigniter4-relations/blob/b964ae2410da9b93c14167b2d396d1768cec9572/src/Traits/ModelTrait.php#L83-L87

Should `$this->with` be casted to array maybe?

### PR DESCRIPTION
**Pull request by sfadschm**
Not sure about the fist check, I think we could check against `null` instead, but this way the previous behavior is preserved.
Fixes #7.

### CODE REVIEW

File: src/Traits/ModelTrait.php [hunk 1]
```diff
@@ -82,7 +82,18 @@ public function without($tables)
...
+			$this->with = [];
+		}
+		
+		// Force a single table name into an array
+		if (!is_array($this->with))
+		{
+			$this->with = [$this->with];
+		}
+
+		return $this->with;
```
Comment (MGatner) [inline src/Traits/ModelTrait.php:96]: Pay attention to styling - we follow CodeIgniter 4's [Style Guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/styleguide.rst).

```suggestion
		// Ensure $this->with is set at all
		if (empty($this->with))
		{
			$this->with = [];
		}
		
		// Force a single table name into an array
		if (! is_array($this->with))
		{
			$this->with = [$this->with];
		}

		return $this->with;
```

**Review by MGatner — CHANGES_REQUESTED** [review]
Looks good! See the style note. Also please apply the same change to `getWithout()`.

File: src/Traits/ModelTrait.php (hunk 1 above)
Comment (sfadschm) [reply src/Traits/ModelTrait.php]: Thanks. Was it just the first curly bracket or also whitespace?

**Review by MGatner — APPROVED** [review]
